# Generated by Django 4.2 on 2025-07-18 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the file', max_length=255)),
                ('file', models.FileField(help_text='The actual file upload', upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the file was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the file was last updated')),
                ('original_owner', models.ForeignKey(help_text='Original owner of the file (for revoke functionality)', on_delete=django.db.models.deletion.CASCADE, related_name='originally_owned_files', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Current owner of the file', on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('TRANSFER', 'Transfer'), ('REVOKE', 'Revoke')], help_text='Type of action performed', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transfer', null=True)),
                ('file', models.ForeignKey(help_text='Reference to the file being transferred', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='file_transfer.file')),
                ('from_user', models.ForeignKey(help_text='User transferring the file', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='User receiving the file', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer History',
                'verbose_name_plural': 'Transfer Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
